# Generated by Django 3.2.9 on 2022-03-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20220311_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleges',
            name='MaximumSAT',
        ),
        migrations.AddField(
            model_name='colleges',
            name='Additionalinformation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='colleges',
            name='Collegwebsite',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='colleges',
            name='CommanApp',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='colleges',
            name='Deadlines',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='colleges',
            name='Informationlink',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='colleges',
            name='MinimumGpa',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='colleges',
            name='Wes',
            field=models.BooleanField(null=True),
        ),
    ]
