# Generated by Django 3.2.9 on 2022-03-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_colleges_scholarshipname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='Deadlines',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='MinimumGpa',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
