# Generated by Django 3.2.9 on 2022-03-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_auto_20220311_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='Additionalinformation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
