# Generated by Django 3.2.9 on 2022-03-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_auto_20220311_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='CommanApp',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='Wes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
