# Generated by Django 3.2.9 on 2022-03-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_auto_20220311_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interview',
            new_name='Essays',
        ),
    ]
