# Generated by Django 3.2.9 on 2022-03-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_rename_interview_essays'),
    ]

    operations = [
        migrations.AddField(
            model_name='essays',
            name='Classof',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='essays',
            name='College',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='essays',
            name='Major',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
